server {
    listen          0.0.0.0:8083;
    server_name     first;
    root            ./www/web1;
    location / {
        allow_methods   GET;
    }
}

server {
    listen          0.0.0.0:8083;
    server_name     second;
    root            ./www/web1;
    location / {
        allow_methods   GET;
    }
}
