server {
    listen              0.0.0.0:8080;
    listen              127.0.0.1:8080;
    server_name         demo.webserv;

    client_max_body_size 5m;

    error_page 400      /error/400.html;
    error_page 403      /error/403.html;
    error_page 404      /error/404.html;
    error_page 405      /error/405.html;
    error_page 413      /error/413.html;
    error_page 500      /error/500.html;
    error_page 502 503 504 /error/50x.html;

    root                ./www/demo;
    index               index.html;

    location / {
        allow_methods   GET;
        autoindex       off;
    }

    location /public {
        allow_methods   GET;
        autoindex       on;
        root            ./www/public;
        index           index.html;
    }

    location /upload {
        allow_methods   POST;
        autoindex       off;
        upload_store    ./www/demo/upload;
    }

    location /old-stuff {
        allow_methods   GET;
        return          301 /public;
    }

    location /old-stuff-2 {
        allow_methods   GET;
        return          302 /public;
    }

    location /api {
        allow_methods   GET POST DELETE;
        autoindex       off;
        root            ./www/api;
        index           api.html;
    }

    location /secret {
        allow_methods   GET;
        autoindex       off;
        root            ./www/demo/secret;
    }

    location /cgi-bin/py {
        allow_methods   GET POST;
        root            ./www/cgi-bin/python;
        cgi_extension   .py;
        autoindex       off;
    }

    location /cgi-bin/php {
        allow_methods   GET POST;
        root            ./www/cgi-bin/php;
        cgi_extension   .php;
        autoindex       off;
    }
}

server {
    listen              0.0.0.0:9090;
    server_name         static.webserv;

    client_max_body_size 1048576;

    error_page 404      /error/404.html;

    root                ./www/static;
    index               index.html;

    location / {
        allow_methods   GET;
        autoindex       on;
    }

    location /assets {
        allow_methods   GET;
        root            ./www/assets;
        autoindex       on;
    }

    location /upload {
        allow_methods   POST;
        upload_store    ./uploads;
    }

    location /redirect {
        return          301 /;
    }
}
