server {
    listen          0.0.0.0:8082;
    server_name     alpha.test;
    root            ./www/web1;
    index           index.html;
    location / {
        allow_methods   GET;
        autoindex       off;
    }
}

server {
    listen          0.0.0.0:8082;
    server_name     beta.test;
    root            ./www/web1/data;
    index           nonexistent.html;
    location / {
        allow_methods   GET;
        autoindex       on;
    }
}
